### ISSUE TITLE
Add support for excluding source fields

### ISSUE THREAD

**Issue by blazing-gig** [dataclass-mapper/dataclass-mapper#21]
Refer to the following code snippet:

```python3

from dataclasses import dataclass
from dataclass_mapper import mapper, map_to


@dataclass
class Person:
    first_name: str
    second_name: str
    full_name: str
    age: int


@mapper(Person)
@dataclass
class ContactInfo:
    first_name: str
    second_name: str
    age: int


p = Person(first_name="hello", second_name="world", full_name="hello world", age=10)

# the following line breaks with an exception
a = map_to(p, ContactInfo) 

```

The exc traceback is as follows:
```
ValueError: 'full_name' of 'Person' has no mapping in 'ContactInfo'
```

Expected / ideal behaviour:

Ability to ignore/exclude fields on source that doesn't have a mapping to target implicitly or explicitly. (Subset of superset)

**Comment by blazing-gig** [comment]
I believe this should be quite easy to implement. @jakobkogler Pls let me know your thoughts as this is quite a prevalent use-case.

**Comment by blazing-gig** [comment]
I realized I read the docs incorrectly and hence had to correct my script. It seems to work now. Closing this.

**Comment by jakobkogler** [comment]
Looks like you figured out the solution yourself already.
But just for completion:

`mapper` is not bidirectional.
If you want to convert a `Person` object into a `ContactInfo`, then you either need to put a `@mapper(ContactInfo)` decorator onto the `Person` class, or a `@mapper_from(Person)` decorator onto the `ContactInfo` class.
