### ISSUE TITLE
"Field type isn't supported" exception for generics despite explicit mapping given for field

### ISSUE THREAD

**Issue by sh-at-cs** [dataclass-mapper/dataclass-mapper#30]
## Steps to reproduce

Consider:

```python
from dataclasses import dataclass
from typing import Generic, TypeVar

from dataclass_mapper import create_mapper

T = TypeVar("T")

class SomeGeneric(Generic[T]):
    pass

@dataclass
class A:
    u: SomeGeneric[int]

@dataclass
class B:
    u: int

create_mapper(A, B, {"u": lambda: 5})
```

As in #28, this results in an exception:

```
TypeError: Field type '__main__.SomeGeneric[int]' is not supported.
```

## Expected behavior

Because an explicit mapping for field `u` was supplied, dataclass-mapper shouldn't care about the source field type at all - by supplying a custom lambda, I made clear that I want to handle it myself. So this should just generate a mapper that maps `u` to `5` and doesn't look at the source field.

## Version info

Tested in version 2.0.0a1.

**Comment by jakobkogler** [comment]
In your example the field `u` in the class `A` is completely unused. 
In such a case I loosened up the checks a bit, so it will not raise any exception any more.
In release [2.0.0a2](https://github.com/dataclass-mapper/dataclass-mapper/releases/tag/v2.0.0a2) the problem doesn't occur any more.

I also allowed another special case, with unsupported types.
If both fields `u` in `A` and `B` are of the same type `SomeGeneric[int]`, you can still map from `A` to `B`. The field value is just copied.

**Comment by sh-at-cs** [comment]
Great, thanks a lot! :slightly_smiling_face: :+1:
