### ISSUE TITLE
Feature suggestion: Typechecking of custom conversion functions

### ISSUE THREAD

**Issue by sh-at-cs** [dataclass-mapper/dataclass-mapper#32]
[The docs mention:](https://dataclass-mapper.readthedocs.io/en/latest/features/custom_conversion_function.html)

>Custom conversion functions are not type-checked. So be careful when using them.

That is, at least to me, one of the major remaining disadvantages of this library compared to writing mappers by hand.

Are there any plans to add type checking for them?

I understand that it's not really possible for conversion functions defined as lambdas, which can't properly have their type signature inspected at runtime (at best, you could do it using extreme hacks that rely on CPython implementation details plus runtime type inference, but let's not even entertain that :slightly_smiling_face:).

But it should be possible for conversion functions defined as named, type-annotated functions. E.g. in a situation like

```python
from dataclasses import dataclass
from uuid import UUID

from dataclass_mapper import create_mapper

@dataclass
class A:
    u: UUID

@dataclass
class B:
    u: int

def u_to_str(self: A) -> str:
    return str(self.u)

create_mapper(A, B, {"u": u_to_str})
```

it should be possible for dataclass-mapper to figure out from `u_to_str`'s signature that the return type doesn't match what is expected. The parameter type could be checked the same way.
Of course, that means anyone who wants to have their custom conversions typechecked would be forced to use named functions everywhere, but at least to me, giving people the option of making that tradeoff is better than having no type checking for them at all.

All alternatives to this approach that I can think of seem worse: Only checking the type when the mapper is called goes against dataclass-mapper's philosophy of performing all type checking prior to this point (which I completely agree with; better performance & earlier detection), while going the other direction and trying to have this checked by static type checkers isn't possible with the static types currently offered by Python (you'd need strange utility types that would make TypeScript blush) - at best, you could write a Mypy plugin, but that leaves Pyright users without any type checking here still.

Thoughts?

**Comment by jakobkogler** [comment]
Yes, checking the signature of custom functions is something on my roadmap.
And as you mentioned, it is not possible for lambdas.

About type checking at runtime.
I would like to really avoid this at all costs.
However I'm thinking of creating a **debug mode**, that checks the types at runtime. E.g. so that you can enable the debug mode for tests, and have higher safety guarantees. And it would also help figuring out errors, when you do something wrong with a lambda. Since the conversion function is "compiled" into bytecode with exec, you can't actually debug when something goes wrong at the moment. And the exception can be a bit meaningless, since you can't see the code.

**Comment by jakobkogler** [comment]
Update: 
I've started with an implementation (#34), and for simple types it already works.
This will definitely be part of the next release.

However it's not so easy to implement it in a very generic way.
E.g. a function that returns a subtype should also be allowed (if the target field is of type `Optional[Union[FooBase, int]]` and the function returns `Foo` where `Foo` inherits from `FooBase`, it's obviously still valid and should be accepted.)
My current implementation still doesn't work for such nested cases, but I'm hopeful that I (have time and) find a solution in the next days.

**Comment by sh-at-cs** [comment]
If you're fine with pulling in a fairly large (~1 MB) dependency, it seems like Beartype's [`beartype.door.is_subhint`](https://beartype.readthedocs.io/en/latest/api_door/#beartype.door.is_subhint) can do these kinds of checks (basically an analogue of `issubclass` that works on static type hints, not just simple types):


```pycon
>>> from beartype.door import is_subhint
>>> is_subhint(int, int|str)
True
>>> is_subhint(list[int], list[int|str])
True
>>> is_subhint(list[int|None], list[int|str])
False
```

I remember searching for something like this several times around 2017-2020 and found nothing, then didn't look into it again until just now, so this is new to me too - no idea if there are any gotchas.

Considering the size, maybe this whole feature could be optional and Beartype could be an optional dependency, same as how Pydantic support is handled right now? Or maybe 1 MB dependencies are fine these days? :thinking: 

I thought that maybe [Typeguard](https://github.com/agronholm/typeguard), which is a much smaller dependency, might also work, considering it has `check_type`, which bills itself as `isinstance` for type hints. But unfortunately, when used in a "quasi-`issubclass`" manner by putting `type[...]` around the second argument, it actually uses `issubclass` under the hood and hence doesn't work for more complex types:

```pycon
>>> from typeguard import check_type
>>> check_type(int, type[int|str])
<class 'int'>
>>> check_type(list[int], type[list[int|str]])
Traceback (most recent call last):
   [...]
    elif not issubclass(value, expected_class):  # type: ignore[arg-type]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() argument 2 cannot be a parameterized generic
```

So it's not an alternative to Beartype for this use case.

No idea if there are other smaller packages that can do this - these are the only ones I found, but then, I'm not very good at this (it also took me forever to find dataclass-mapper itself).

**Comment by sh-at-cs** [comment]
I guess one obvious gotcha of `beartype.door.is_subhint` that I missed above is that it doesn't even match static typing behavior for the example I gave - `list[int]` shouldn't be a subtype of `list[int|str]` because `list` is invariant.

They already have an issue for that: https://github.com/beartype/beartype/issues/190

So I don't know...

**Comment by jakobkogler** [comment]
I've actually already have a custom written type checker in the library. 
It's used to deconstruct complicated types, so that also nested mappings are possible. 
E.g. you can map between the fields `x: list[Foo]` to `y: list[Bar]`, if there is a mapping defined between `Foo` and `Bar`. The `dataclass-mapper` already deconstructed the types, and checked if there is a way to map between these two (this actually is possible over multiple levels).

I've reused parts of it for the type checking of callables (and also extended it a bit - until now it was not possible to map a subtype field to a supertype field).

In [v2.0.0a4](https://github.com/dataclass-mapper/dataclass-mapper/releases/tag/v2.0.0a4) types of callables are now type checked (if they contain type annotations).
Docs: https://dataclass-mapper.readthedocs.io/en/latest/type_safety.html#type-checks-of-custom-conversion-functions

**Comment by jakobkogler** [comment]
There is one potential bug in there. But I'm a bit unsure if this is actually common/expected or not.

I'm assuming that `list[int]` is a subtype of `list[int | str]`.
I've used this definition also already during the normal mappings, however there it was never a problem as I deconstructed the old type into all it's bits, and reconstructed the final instance at the end. That ended up in a shallow copy of the list, and all is fine (at least I think so).

Here the situation is a bit different, as I just assign the result of the function to the field in the target class.
Which might have some strange effects as the list type is invariant.
The following code is completely types, gives no Mypy error, and we also don't get any typeerror from the `dataclass-mapper` library.
Still it's very easy to add the wrong type to the list in the source class.

```python
@dataclass
class Source:
    lst: list[int]

@dataclass
class Target:
    lst: list[int | str]


def extract_list(source: Source) -> list[int]:
    return source.lst

create_mapper(Source, Target, {"lst": extract_list})


source = Source([1, 2, 3])
target = map_to(source, Target)

target.lst.append("abc")

print(source.lst)
# [1, 2, 3, "abc"] even though the type is marked as `list[int]`
```

A potential solution would be, to just make a shallow copy of the return value as well.

**Comment by sh-at-cs** [comment]
Amazing, thanks once again! :slightly_smiling_face: 

So this issue can be closed, right?

Regarding invariance: My guess is that bugs that stem from this would be very rare; e.g. in your example, the much bigger issue is that the user maps a mutable data structure without making a copy and then keeps working with the source instance, which, if someone did this in reality, would almost definitely be a bug, and which type checking can't help prevent anyway (maybe Python needs a borrow checker like Rust to prevent this :slightly_smiling_face:).

Personally, I don't think automatically making a shallow copy of the list is what users would expect, because custom conversions are understood to be "fully manual" without dataclass-mapper interfering (beyond initial type checking).

Is it possible for lack of invariance handling to cause issues in code that doesn't have such bigger issues anyway? :thinking: 

Even then, I'd say it's probably fine for that to be a limitation for the time being. Maybe there could be another issue about it, just so people can find it in the issue list if they do run into it.

**Comment by jakobkogler** [comment]
I agree. The bug will only occur in very rare situations.

I've created a follow up #35, so that we can close this feature request.
